package com.dao.userinfo;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "USER".
 */
public class User {

    /** Not-null value. */
    private String uid;
    private String token;
    private String nickname;

    public User() {
    }

    public User(String uid) {
        this.uid = uid;
    }

    public User(String uid, String token, String nickname) {
        this.uid = uid;
        this.token = token;
        this.nickname = nickname;
    }

    /** Not-null value. */
    public String getUid() {
        return uid;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setUid(String uid) {
        this.uid = uid;
    }

    public String getToken() {
        return token;
    }

    public void setToken(String token) {
        this.token = token;
    }

    public String getNickname() {
        return nickname;
    }

    public void setNickname(String nickname) {
        this.nickname = nickname;
    }

}
